### ISSUE TITLE
Not clicking 'Go' once map is selected, phone with adb debugging.

### ISSUE THREAD

**Issue by KiLockServiceTable** [perryhuynh/azurlane-auto#7]
Tried using the combat module on my phone with adb debugging enabled.
 
First, it didn't properly tap on 'Attack' because of the resolution, changed it to 720x1280 and solved that issue. After that, it properly taps on the 6-1 map but it gets stuck when having to tap on the second 'Go', on the fleet screen. 

Tried restarting 3 times, one of them didn't tap on the second go, the other two times it didn't even click on the first one.

The console doesn't detect the issue and acts like it properly entered the map.
```
[2018-12-25 19:04:22] Navigating to map.
[2018-12-25 19:04:42] Alternate clearing fleet enabled, switching to 2nd fleet to clear trash
```
The second line happens 10s after entering the second go screen, it taps outside and closes the box.

My config.ini (ignore the KillsNeeded part, I intended to use it on 10-4 at first):
```
[Commissions]
Enabled: True

[Combat]
Enabled: True
Map: 6-1
KillsNeeded: 6
Hard: False
Formation:
AltClearFleet: True
BossFleet: True

[Missions]
Enabled: False
```
Tried disabling AltClearFleet and BossFleet just in case, still doesn't work and does exactly the same (which I kinda expected, since those settings only affect once it has entered the map).

**Comment by perryhuynh** [comment]
Hmm I might not have a put a long enough delay between the clicking of the Go buttons since I used hard-coded coordinates instead of an image for those, If you want to test for now you can change Line 61 of `modules/combat.py` to `Utils.script_sleep(3)`.

I'm currently in the process of adding more robust logging as well as fixing some of the combat logic which should hopefully be available soon that should resolve crashing when the boss is unreachable as well as this issue. I'll also be adding the rest of the maps hopefully soon as I've been a bit lazy and still haven't even cleared W9

**Comment by KiLockServiceTable** [comment]
I think I found the issue, when resizing the screen on my phone it does leave some black edges when pulling screenshots from adb. 
I tried restarting the phone and although the black edges become semi-unusable from phone itself (checked by enabling show taps and tapping on those zones, edit: if you tap fast enough you can still see the taps on those zones, so nvm) it keeps appearing on screencaps.

Been searching on google if there's any way to solve this, but there ain't much information regarding this. All I found is a command which seems to change your physical screen resolution, but isn't usable anymore after android 4.3.

**Comment by perryhuynh** [comment]
Hmm you might have to use an emulator then, the best one I've found is the official Android Studio emulator (which was also the only emulator I tested it on)

**Comment by KiLockServiceTable** [comment]
Will try now, thanks.
Btw, is there any better place to communicate with you more directly? I would like to help you as a tester.

**Comment by perryhuynh** [comment]
You can add me on discord @ Perry#9205 if you have that

**Comment by KiLockServiceTable** [comment]
https://i.imgur.com/3COokPc.png
Here you have mine: Shirome#4083.
