### ISSUE TITLE
Can't find specified file

### ISSUE THREAD

**Issue by LazyBoii** [perryhuynh/azurlane-auto#8]
#### Environment details

0.1.1

#### Issue variability

Consistent

#### Issue

Running the command  : python3 azurlane-auto.py always ends with FileNotFoundError: [WinError 2]

![azur](https://user-images.githubusercontent.com/46345793/50635837-cf6ee700-0f21-11e9-9f88-e16d05f27ebb.PNG)

#### Log
```
C:\Users\imaik\Downloads\Azur Lane\azurlane-auto-master>py -3 azurlane-auto.py
[94m[2019-01-03 06:29:48] Initializing config module[0m
[94m[2019-01-03 06:29:48] Validating config[0m
[94m[2019-01-03 06:29:48] Starting azurlane-auto![0m
Traceback (most recent call last):
  File "azurlane-auto.py", line 91, in <module>
    Adb.init()
  File "C:\Users\imaik\Downloads\Azur Lane\azurlane-auto-master\util\adb.py", line 10, in init
    cls.kill_server()
  File "C:\Users\imaik\Downloads\Azur Lane\azurlane-auto-master\util\adb.py", line 25, in kill_server
    subprocess.call(cmd)
  File "C:\Users\imaik\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 323, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Users\imaik\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "C:\Users\imaik\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by perryhuynh** [comment]
You don't have ADB installed on your system and/or on your PATH, I'll probably end up trying including the ADB binaries in the project so people don't have to install it themselves.

EDIT: It looks like I forgot to mention ADB installation in the README so I will update that as well if including the binary doesn't work.

**Comment by LazyBoii** [comment]
hmm, its weird because I have adb installed, also added it to my path just now and still get same error, possibly missing something else.

**Comment by perryhuynh** [comment]
Dunno if you have to restart the computer for it to apply on Windows but ADB works if you type `adb` in command prompt?

**Comment by LazyBoii** [comment]
Says its not recognized let me restart my computer.

**Edit:** ok its all set now i had the wrong adb binaries, had to update them, but ya adding the adb binaries/ mention in readme will help people who overlook that :D

**Comment by LazyBoii** [comment]
ok its all set now i had the wrong adb binaries, had to update them
